### ISSUE TITLE
Can't compile project from source

### ISSUE THREAD

**Issue by Doggysus** [ZaksenCode/DeathLabyrinth#1]
when I try to compile a project from source code, I get this error message

``[dogsfox@dg DeathLabyrinth-master]$ ./gradlew
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain``

**Comment by ZaksenCode** [comment]
Not sure what problem there. Looks like GradleWrapper is not working properly. Try some of these: [StackOverflow](https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain.)
